# Generated by Django 4.0.3 on 2022-06-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('Name', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
